// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAppData(arg1:string,arg2:string):Promise<string>;

export function DisableApp(arg1:string,arg2:string):Promise<string>;

export function EnableApp(arg1:string,arg2:string):Promise<string>;

export function ExportAPK(arg1:string,arg2:string):Promise<string>;

export function ForceStopApp(arg1:string,arg2:string):Promise<string>;

export function GetDevices():Promise<Array<main.Device>>;

export function Greet(arg1:string):Promise<string>;

export function InstallAPK(arg1:string,arg2:string):Promise<string>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<main.AppPackage>>;

export function RunAdbCommand(arg1:Array<string>):Promise<string>;

export function StartApp(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string):Promise<void>;

export function StartScrcpy(arg1:string,arg2:main.ScrcpyConfig):Promise<void>;

export function StopLogcat():Promise<void>;

export function UninstallApp(arg1:string,arg2:string):Promise<string>;
